Algoritmo "REPITA1ATE10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/07/2023
Var
// Seção de Declarações das variáveis
    i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
    i<-1
    REPITA
      ESCREVAL ("Valor de I: ", i)
      i<-i+1
    ATE i>=10

Fimalgoritmo