algoritmo "modelorepeticaodeprograma"
 //Nesse modelo serve para copiar e colar no programa que deseja ter a
 //mensagem avisando que o programa será repetido ou personanizar
var
   repetir: caractere

inicio
   repetir <- "S"

   enquanto repetir = "S" faca
      // Seu código aqui
      escreva("O programa será repetido. Deseja continuar (S/N)? ")
      leia(repetir)
   fimenquanto

   escreval("Fim do programa.")
   
Fimalgoritmo
